# Site settings
title: Florence As It Was&#58;
subtitle: the Digital Reconstruction of a Medieval City
email: bentg@wlu.edu
description: A Washington & Lee Digital Humanities Project
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://florenceasitwas.wlu.edu" # the base hostname & protocol for your site
author:
street_address: 204 W. Washington St.
city: Lexington
state: VA
zip_code: 24450
country: United States of America
phone: (540) 458-8400

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
excerpt_separator: <!-- read more -->

# Collections
collections:
  contributors:
    output: true
    permalink: /contributors/:name
  people:
    output: true
    permalink: /people/:name
  buildings:
    output: true
    permalink: /buildings/:name
  artworks:
    output: true
    permalink: /artwork/:name
  locations:
    output: true
    permalink: /locations/:name
  texts:
    output: true
    permalink: /texts/:name
